# Test Name: firstTest.txt (iteration 0)
# Generated by TheFuzz v1.0.0 written by Alex Kersten and Kenneth Siu for ECE552 (https://github.com/akersten/TheFuzz)
Spring 2015 Functionality Added by Sam Schwebach

  LLB R10, 119                   #; R10=119
  LLB R9, 100                    #; R9=100
  SLL R7, R0, 1                  #; (0<<1=0); Z->1
  LHB R11, 61                    #; R11=15616
  NAND R12, R10, R9              #; (119&100=-101); Z->0; N->0; V->0
  SRL R7, R7, 7                  #; (0>>7=0); Z->1
  SUB R2, R11, R0                #; (15616-0=15616); Z->0; N->0; V->0
  SUB R7, R0, R9                 #; (0-100=-100); Z->0; N->1; V->0
  SRA R13, R2, 4                 #; (15616>>>4=976); Z->0
  SRA R1, R13, 5                 #; (976>>>5=30); Z->0
  SRL R4, R0, 2                  #; (0>>2=0); Z->1
  LLB R13, 45                    #; R13=45
  SRA R12, R10, 7                #; (119>>>7=0); Z->1
  SRL R8, R10, 0                 #; (119>>0=119); Z->0
  LHB R4, 28                     #; R4=7168
  SUB R3, R11, R4                #; (15616-7168=8448); Z->0; N->0; V->0
  LLB R1, 11                     #; R1=11
  SRL R8, R11, 4                 #; (15616>>4=976); Z->0
  ADD R9, R11, R11               #; (15616+15616=31232); Z->0; N->0; V->0
  SRA R11, R11, 2                #; (15616>>>2=3904); Z->0
  ADD R3, R0, R10                #; (0+119=119); Z->0; N->0; V->0
  NAND R3, R8, R2                #; (976&15616=-257); Z->0; N->0; V->0
  ADD R0, R8, R3                 #; (976+-257=719); No change to R0; Z->0; N->0; V->0
  SRA R1, R2, 6                  #; (15616>>>6=244); Z->0
  SRA R2, R9, 1                  #; (31232>>>1=15616); Z->0
  SRA R5, R9, 4                  #; (31232>>>4=1952); Z->0
  SLL R2, R1, 7                  #; (244<<7=31232); Z->0
  LLB R13, 29                    #; R13=29
  SUB R2, R3, R8                 #; (-257-976=-1233); Z->0; N->1; V->0
  SRL R11, R8, 7                 #; (976>>7=7); Z->0
  HLT                            #; 

# R0 = 0
# R1 = 244
# R2 = -1233
# R3 = -257
# R4 = 7168
# R5 = 1952
# R6 = xxxx
# R7 = -100
# R8 = 976
# R9 = 31232
# R10 = 119
# R11 = 7
# R12 = 0
# R13 = 29
# R14 = xxxx
# R15 = xxxx

# Z = 0 N = 1 V = 0

# Valid memory addresses:
