# Test Name: testint.txt (iteration 0)
# Generated by TheFuzz v1.0.0 written by Alex Kersten and Kenneth Siu for ECE552 (https://github.com/akersten/TheFuzz)

  B EQ, nottaken                 #; branch on EQ, take = no
  LLB R6, 32                     #; R6=32
  SUB R7, R6, R6                 #; (32-32=0); Z->1; N->0; V->0
  LHB R13, 117                   #; R13=29952
  LLB R12, 124                   #; R12=124
  SUB R4, R0, R12                #; (0-124=-124); Z->0; N->1; V->0
  ADD R8, R13, R7                #; (29952+0=29952); Z->0; N->0; V->0
  LHB R12, 42                    #; R12=10876
  LLB R5, 116                    #; R5=116
  LHB R2, 53                     #; R2=13568
  SUB R6, R0, R13                #; (0-29952=-29952); Z->0; N->1; V->0
  SUB R5, R0, R5                 #; (0-116=-116); Z->0; N->1; V->0
  LLB R6, 113                    #; R6=113
  ADD R4, R5, R7                 #; (-116+0=-116); Z->0; N->1; V->0
  LHB R1, 49                     #; R1=12544
  ADD R14, R5, R7                #; (-116+0=-116); Z->0; N->1; V->0
  SUB R13, R13, R0               #; (29952-0=29952); Z->0; N->0; V->0
  ADD R3, R6, R8                 #; (113+29952=30065); Z->0; N->0; V->0
  B NEQ, taken1                  #; branch on NEQ, take = yes
fail2:                           #
  HLT                            #
taken1:                          #
  B LT, nottaken                 #; branch on LT, take = no
nottaken:                        #; failure case for wrongly taken branches
  HLT                            #; 

# R0 = 0
# R1 = 12544
# R2 = 13568
# R3 = 30065
# R4 = -116
# R5 = -116
# R6 = 113
# R7 = 0
# R8 = 29952
# R9 = xxxx
# R10 = xxxx
# R11 = xxxx
# R12 = 10876
# R13 = 29952
# R14 = -116
# R15 = xxxx

# Z = 0 N = 0 V = 0

# Valid memory addresses:
